export const PRODUCT_REQUEST = "PRDUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT"